import * as vscode from 'vscode';

/**
 * Generator for the standard Terraform module repository skeleton (USAGE.md
 * Pattern 1 — "One repository per Terraform module").
 *
 * Pure-string generation lives in {@link generateModuleRepoFiles} so it can be
 * unit-tested without a workspace. {@link writeModuleRepoFiles} performs the
 * actual disk writes and is invoked from the chat tool / command handler.
 */

export interface ScaffoldModuleRepoOptions {
  /** Module repo name, e.g. `terraform-aws-vpc`. Drives README headings. */
  moduleName: string;
  /** Provider key, e.g. `aws`, `azurerm`, `google`. Drives `versions.tf`. */
  provider: string;
  /** Optional one-line description for the README. */
  description?: string;
  /** Folder names under `examples/` to scaffold. Defaults to `['basic']`. */
  exampleNames?: string[];
  /** Include a `.devcontainer/devcontainer.json`. Defaults to `false`. */
  includeDevcontainer?: boolean;
  /** Pin a minimum Terraform/OpenTofu version. Defaults to `>= 1.5.0`. */
  requiredVersion?: string;
}

/** Map of provider key → `required_providers` entry. */
const PROVIDER_DEFAULTS: Record<string, { source: string; version: string }> = {
  aws: { source: 'hashicorp/aws', version: '~> 5.0' },
  azurerm: { source: 'hashicorp/azurerm', version: '~> 3.0' },
  google: { source: 'hashicorp/google', version: '~> 5.0' },
  kubernetes: { source: 'hashicorp/kubernetes', version: '~> 2.0' },
  helm: { source: 'hashicorp/helm', version: '~> 2.0' },
  github: { source: 'integrations/github', version: '~> 6.0' },
  null: { source: 'hashicorp/null', version: '~> 3.0' },
};

function providerEntry(provider: string): { source: string; version: string } {
  const key = provider.toLowerCase();
  if (PROVIDER_DEFAULTS[key]) return PROVIDER_DEFAULTS[key];
  // Fallback: assume hashicorp namespace, no constraint pinned.
  return { source: `hashicorp/${key}`, version: '>= 0.0.0' };
}

function versionsTf(provider: string, requiredVersion: string): string {
  const { source, version } = providerEntry(provider);
  return `terraform {
  required_version = "${requiredVersion}"
  required_providers {
    ${provider} = {
      source  = "${source}"
      version = "${version}"
    }
  }
}
`;
}

function mainTf(moduleName: string): string {
  return `# ${moduleName}
#
# Module entry point. Declare resources here. Inputs go in variables.tf,
# outputs in outputs.tf, provider/version constraints in versions.tf.
`;
}

function variablesTf(): string {
  return `# Module inputs.
#
# Example:
#
# variable "name" {
#   description = "Name tag applied to all resources."
#   type        = string
# }
`;
}

function outputsTf(): string {
  return `# Module outputs.
#
# Example:
#
# output "id" {
#   description = "ID of the created resource."
#   value       = aws_xxx.this.id
# }
`;
}

function exampleMainTf(moduleName: string): string {
  // Local module name is the part after the last "-" in moduleName, or the
  // whole name if it doesn't follow the terraform-<provider>-<thing> convention.
  const parts = moduleName.split('-');
  const localName = parts.length >= 3 ? parts.slice(2).join('_') : moduleName.replace(/-/g, '_');
  return `module "${localName}" {
  source = "../../"

  # Pass module inputs here.
}
`;
}

function exampleVersionsTf(provider: string, requiredVersion: string): string {
  // Examples need their own provider block since they're a separate root module.
  const { source, version } = providerEntry(provider);
  return `terraform {
  required_version = "${requiredVersion}"
  required_providers {
    ${provider} = {
      source  = "${source}"
      version = "${version}"
    }
  }
}

provider "${provider}" {
  # Configure the provider here, or rely on environment variables / shared config.
}
`;
}

function readmeMd(opts: ScaffoldModuleRepoOptions): string {
  const tagline = opts.description ?? `Terraform module for ${opts.provider}.`;
  const exampleLinks = (opts.exampleNames ?? ['basic'])
    .map(n => `- [\`examples/${n}\`](./examples/${n})`)
    .join('\n');
  return `# ${opts.moduleName}

${tagline}

## Usage

\`\`\`hcl
module "${opts.moduleName.replace(/-/g, '_')}" {
  source = "git::https://github.com/<org>/${opts.moduleName}.git?ref=v0.1.0"

  # Inputs go here.
}
\`\`\`

## Examples

${exampleLinks}

<!-- BEGIN_TF_DOCS -->
<!-- This block is auto-generated by terraform-docs. Do not edit by hand.
     Run \`terraform-docs markdown table --output-file README.md --output-mode inject .\`
     or wire up the GitHub Action: terraform-docs/gh-actions. -->
<!-- END_TF_DOCS -->
`;
}

function gitignore(): string {
  return `# Local .terraform directories
**/.terraform/*

# .tfstate files
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Variables files that may contain secrets
*.tfvars
*.tfvars.json

# Terraform CLI plan output
*.tfplan
*.tfplan.binary

# Override files (likely user-specific)
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Lock files (uncomment to ignore — usually you want to commit these)
# .terraform.lock.hcl
`;
}

function terraformDocsConfig(): string {
  return `# terraform-docs configuration.
# See https://terraform-docs.io/user-guide/configuration/ for the full reference.
formatter: "markdown table"

sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs
    - resources
    - modules

content: |-
  {{ .Header }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
`;
}

function devcontainerJson(): string {
  return `{
  "name": "Terraform Module Dev",
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
  "features": {
    "ghcr.io/devcontainers/features/terraform:1": {},
    "ghcr.io/devcontainers/features/github-cli:1": {}
  },
  "customizations": {
    "vscode": {
      "extensions": [
        "hashicorp.terraform",
        "HappyPathway.terraform-workspace"
      ]
    }
  }
}
`;
}

/**
 * Returns the full set of files (relative POSIX path → contents) that make up
 * a new Terraform module repo. Pure — performs no IO.
 */
export function generateModuleRepoFiles(
  options: ScaffoldModuleRepoOptions,
): Map<string, string> {
  const opts: Required<ScaffoldModuleRepoOptions> = {
    moduleName: options.moduleName,
    provider: options.provider,
    description: options.description ?? '',
    exampleNames: options.exampleNames?.length ? options.exampleNames : ['basic'],
    includeDevcontainer: options.includeDevcontainer ?? false,
    requiredVersion: options.requiredVersion ?? '>= 1.5.0',
  };

  const files = new Map<string, string>();
  files.set('main.tf', mainTf(opts.moduleName));
  files.set('variables.tf', variablesTf());
  files.set('outputs.tf', outputsTf());
  files.set('versions.tf', versionsTf(opts.provider, opts.requiredVersion));
  files.set('README.md', readmeMd(opts));
  files.set('.gitignore', gitignore());
  files.set('.terraform-docs.yml', terraformDocsConfig());

  for (const name of opts.exampleNames) {
    files.set(`examples/${name}/main.tf`, exampleMainTf(opts.moduleName));
    files.set(`examples/${name}/versions.tf`, exampleVersionsTf(opts.provider, opts.requiredVersion));
  }

  if (opts.includeDevcontainer) {
    files.set('.devcontainer/devcontainer.json', devcontainerJson());
  }

  return files;
}

export interface WriteModuleRepoFilesResult {
  /** Files newly written to disk. */
  written: string[];
  /** Files skipped because they already existed and `overwrite` was false. */
  skipped: string[];
  /** Files overwritten because `overwrite` was true. */
  overwritten: string[];
}

/**
 * Writes the generated module-repo skeleton under `targetUri`. If a file
 * already exists and `overwrite` is false, it's left untouched and reported
 * in `skipped`. Directories are created as needed.
 */
export async function writeModuleRepoFiles(
  targetUri: vscode.Uri,
  options: ScaffoldModuleRepoOptions,
  overwrite: boolean,
): Promise<WriteModuleRepoFilesResult> {
  const files = generateModuleRepoFiles(options);
  const result: WriteModuleRepoFilesResult = { written: [], skipped: [], overwritten: [] };
  const encoder = new TextEncoder();

  for (const [relPath, content] of files) {
    const fileUri = vscode.Uri.joinPath(targetUri, ...relPath.split('/'));
    let exists = false;
    try {
      await vscode.workspace.fs.stat(fileUri);
      exists = true;
    } catch {
      exists = false;
    }
    if (exists && !overwrite) {
      result.skipped.push(relPath);
      continue;
    }
    // vscode.workspace.fs.writeFile creates parent directories automatically.
    await vscode.workspace.fs.writeFile(fileUri, encoder.encode(content));
    if (exists) result.overwritten.push(relPath);
    else result.written.push(relPath);
  }

  return result;
}
