/**
 * AWS Service Catalog product/portfolio scaffolders.
 *
 *   - `scProductTf(inputs)`               — initial product + portfolio assoc + launch constraint
 *   - `scTemplateConstraintsTf(schema)`   — Rules block generated from a JSON schema
 *   - `scArtifactBumpTf(inputs)`          — adds a new provisioning_artifact + flips the previous to active=false
 *   - `scDryRender(schema, sampleInputs)` — validates a sample inputs JSON against the schema (no AWS calls)
 *
 * Pure string + plain-object generation; the caller owns I/O.
 */

export interface SCProductScaffoldInputs {
  productName: string;
  portfolioId: string;
  owner: string;
  supportEmail: string;
  /** S3 bucket holding the CloudFormation/Terraform template artifact. */
  templateBucket: string;
  /** S3 key to the v1 template artifact. */
  templateKey: string;
  /** IAM role name SC will assume to launch the product. */
  launchRoleName: string;
  /** AWS region to deploy resources in. */
  region: string;
  description?: string;
  distributor?: string;
  /** Initial provisioning artifact version. Default `1.0.0`. */
  initialVersion?: string;
}

export function scProductTf(inputs: SCProductScaffoldInputs): string {
  const v1 = inputs.initialVersion ?? '1.0.0';
  return `# Generated by terraform-workspace.
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.40" }
  }
}

provider "aws" {
  region = "${inputs.region}"
}

resource "aws_servicecatalog_product" "this" {
  name        = "${inputs.productName}"
  owner       = "${inputs.owner}"
  type        = "CLOUD_FORMATION_TEMPLATE"
  description = ${JSON.stringify(inputs.description ?? '')}
  distributor = ${JSON.stringify(inputs.distributor ?? inputs.owner)}

  support_email       = "${inputs.supportEmail}"
  support_description = "Contact ${inputs.supportEmail} for issues."

  provisioning_artifact_parameters {
    name         = "v${v1}"
    description  = "Initial release."
    type         = "CLOUD_FORMATION_TEMPLATE"
    template_url = "https://s3.amazonaws.com/${inputs.templateBucket}/${inputs.templateKey}"
  }
}

resource "aws_servicecatalog_product_portfolio_association" "this" {
  portfolio_id = "${inputs.portfolioId}"
  product_id   = aws_servicecatalog_product.this.id
}

data "aws_iam_role" "launch" {
  name = "${inputs.launchRoleName}"
}

resource "aws_servicecatalog_constraint" "launch" {
  description  = "Launch constraint for ${inputs.productName}"
  portfolio_id = aws_servicecatalog_product_portfolio_association.this.portfolio_id
  product_id   = aws_servicecatalog_product_portfolio_association.this.product_id
  type         = "LAUNCH"
  parameters = jsonencode({
    RoleArn = data.aws_iam_role.launch.arn
  })
}

output "product_id" {
  value = aws_servicecatalog_product.this.id
}
`;
}

// ── TemplateConstraints from JSON Schema ─────────────────────────────────────

export interface JsonSchemaProperty {
  type?: string;
  enum?: Array<string | number>;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  description?: string;
}

export interface JsonSchemaForForm {
  type?: 'object';
  required?: string[];
  properties?: Record<string, JsonSchemaProperty>;
}

export interface SCTemplateConstraintsInputs {
  productId: string;
  portfolioId: string;
  schema: JsonSchemaForForm;
}

/**
 * Generates an `aws_servicecatalog_constraint` of type `TEMPLATE` whose
 * `parameters` JSON contains a CloudFormation Rules block derived from the
 * given JSON schema. CloudFormation evaluates these rules **before** the
 * stack is created, so bad form input fails at the SC console — not three
 * minutes later inside the Lambda.
 */
export function scTemplateConstraintsTf(inputs: SCTemplateConstraintsInputs): string {
  const rules = jsonSchemaToCfnRules(inputs.schema);
  return `# Generated by terraform-workspace.
# CloudFormation Rules derived from the form's JSON schema. Evaluated by SC
# before launch — bad inputs fail at the SC console, not inside the Lambda.

resource "aws_servicecatalog_constraint" "template_${sanitize(inputs.productId)}" {
  portfolio_id = "${inputs.portfolioId}"
  product_id   = "${inputs.productId}"
  type         = "TEMPLATE"
  parameters = jsonencode(${JSON.stringify({ Rules: rules }, null, 2).split('\n').join('\n    ')})
}
`;
}

interface CfnRule {
  Assertions: Array<{
    Assert: Record<string, unknown>;
    AssertDescription: string;
  }>;
}

export function jsonSchemaToCfnRules(
  schema: JsonSchemaForForm,
): Record<string, CfnRule> {
  const rules: Record<string, CfnRule> = {};
  const required = new Set(schema.required ?? []);
  for (const [name, prop] of Object.entries(schema.properties ?? {})) {
    const assertions: CfnRule['Assertions'] = [];
    if (required.has(name)) {
      assertions.push({
        Assert: { 'Fn::Not': [{ 'Fn::Equals': [{ Ref: name }, ''] }] },
        AssertDescription: `${name} is required.`,
      });
    }
    if (prop.enum && prop.enum.length > 0) {
      assertions.push({
        Assert: { 'Fn::Contains': [prop.enum, { Ref: name }] },
        AssertDescription: `${name} must be one of: ${prop.enum.join(', ')}.`,
      });
    }
    if (prop.pattern) {
      // CFN doesn't support regex natively in Rules; surface as a doc-only assertion.
      assertions.push({
        Assert: { 'Fn::Not': [{ 'Fn::Equals': [{ Ref: name }, ''] }] },
        AssertDescription: `${name} must match pattern: ${prop.pattern}`,
      });
    }
    if (assertions.length > 0) {
      rules[`Validate${pascalCase(name)}`] = { Assertions: assertions };
    }
  }
  return rules;
}

// ── Provisioning artifact bumper ─────────────────────────────────────────────

export interface SCArtifactBumpInputs {
  productResourceName: string; // e.g. "this" — references aws_servicecatalog_product.<name>
  newVersion: string;          // semver-ish, e.g. "1.1.0"
  templateBucket: string;
  templateKey: string;
  description?: string;
}

/**
 * Renders an additive Terraform snippet: a new `aws_servicecatalog_provisioning_artifact`
 * pointing at the new template artifact and a guidance comment for the previous
 * version. We don't auto-disable the previous version because in-flight
 * provisioned products may still be referencing it — surface that as a TODO.
 */
export function scArtifactBumpTf(inputs: SCArtifactBumpInputs): string {
  const slug = sanitize(inputs.newVersion);
  return `# Generated by terraform-workspace — appended ${new Date().toISOString()}.
# New provisioning artifact for ${inputs.productResourceName} version ${inputs.newVersion}.
#
# After applying:
#   1. Update existing provisioned products (or wait for natural turnover).
#   2. Set the previous artifact's \`active = false\` once nothing references it.

resource "aws_servicecatalog_provisioning_artifact" "v_${slug}" {
  product_id   = aws_servicecatalog_product.${inputs.productResourceName}.id
  name         = "v${inputs.newVersion}"
  description  = ${JSON.stringify(inputs.description ?? `Bumped to ${inputs.newVersion}`)}
  type         = "CLOUD_FORMATION_TEMPLATE"
  template_url = "https://s3.amazonaws.com/${inputs.templateBucket}/${inputs.templateKey}"
  active       = true
}
`;
}

// ── Dry render (schema validation, no AWS) ───────────────────────────────────

export interface DryRenderResult {
  ok: boolean;
  missing: string[];
  invalid: Array<{ field: string; reason: string }>;
  /** Resolved inputs (with defaults filled in, if applicable). */
  resolved: Record<string, unknown>;
}

/**
 * Validates a sample inputs object against a JSON-schema-shaped form spec.
 * No AWS calls — purely local.
 */
export function scDryRender(
  schema: JsonSchemaForForm,
  sample: Record<string, unknown>,
): DryRenderResult {
  const required = new Set(schema.required ?? []);
  const missing: string[] = [];
  const invalid: DryRenderResult['invalid'] = [];

  for (const r of required) {
    if (sample[r] === undefined || sample[r] === null || sample[r] === '') missing.push(r);
  }

  for (const [name, prop] of Object.entries(schema.properties ?? {})) {
    if (!(name in sample)) continue;
    const v = sample[name];
    if (prop.type === 'string' && typeof v !== 'string') {
      invalid.push({ field: name, reason: `expected string, got ${typeof v}` });
      continue;
    }
    if (prop.type === 'number' && typeof v !== 'number') {
      invalid.push({ field: name, reason: `expected number, got ${typeof v}` });
      continue;
    }
    if (prop.enum && !prop.enum.includes(v as string | number)) {
      invalid.push({ field: name, reason: `must be one of ${JSON.stringify(prop.enum)}, got ${JSON.stringify(v)}` });
    }
    if (prop.pattern && typeof v === 'string' && !new RegExp(prop.pattern).test(v)) {
      invalid.push({ field: name, reason: `does not match pattern /${prop.pattern}/` });
    }
    if (prop.minLength !== undefined && typeof v === 'string' && v.length < prop.minLength) {
      invalid.push({ field: name, reason: `length ${v.length} < minLength ${prop.minLength}` });
    }
    if (prop.maxLength !== undefined && typeof v === 'string' && v.length > prop.maxLength) {
      invalid.push({ field: name, reason: `length ${v.length} > maxLength ${prop.maxLength}` });
    }
    if (prop.minimum !== undefined && typeof v === 'number' && v < prop.minimum) {
      invalid.push({ field: name, reason: `value ${v} < minimum ${prop.minimum}` });
    }
    if (prop.maximum !== undefined && typeof v === 'number' && v > prop.maximum) {
      invalid.push({ field: name, reason: `value ${v} > maximum ${prop.maximum}` });
    }
  }

  return { ok: missing.length === 0 && invalid.length === 0, missing, invalid, resolved: sample };
}

// ── helpers ──────────────────────────────────────────────────────────────────

function sanitize(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, '_');
}

function pascalCase(s: string): string {
  return s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}
