/**
 * Generators for an AWS Lambda container image pipeline that mirrors the
 * Terraform CodeBuild executor pattern (see `src/workflows/Scaffolders.ts`):
 *
 *   - A Packer template (`packer.pkr.hcl`) that builds the function image
 *     using the amazon-ecr source.
 *   - A `build.hcl` consumed by the existing `packer-pipeline` CLI / CodeBuild
 *     project, so users keep using their already-provisioned image-build
 *     pipeline rather than us reinventing one.
 *   - Terraform: ECR repo (lifecycle policy), IAM exec role, and
 *     `aws_lambda_function` with `package_type = "Image"` pinned by digest
 *     via a `var.image_digest` so the next `terraform apply` after a fresh
 *     image build picks it up deterministically.
 *   - A `src/handler.py` skeleton (only written if missing).
 *
 * Patterns match the lambda-template-repo-generator deploy/ workspace:
 *   - data.aws_partition.current for partition-aware ARNs (works in GovCloud)
 *   - VPC config via subnet/SG lookup by Name tag
 *   - Optional CodeBuild project resource that the Lambda can trigger
 *   - IAM policies for Lambda→CodeBuild and Lambda→Secrets Manager
 *
 * Pure string generation — no I/O. The caller is responsible for writing
 * files, prompting the user, etc.
 */

export interface LambdaImageScaffoldInputs {
  /** Logical function name. Used for the directory, ECR repo, and Lambda name. */
  functionName: string;
  /** AWS region the Lambda + ECR repo live in. */
  region: string;
  /** S3 bucket + key the packer-pipeline CodeBuild project reads sources from. */
  packerSourceBucket: string;
  /** Name of the existing packer-pipeline CodeBuild project to dispatch into. */
  packerCodebuildProject: string;
  /** Base image for the Lambda runtime. Default: `public.ecr.aws/lambda/python:3.12`. */
  baseImage?: string;
  /** Lambda handler entrypoint. Default: `handler.lambda_handler`. */
  handler?: string;
  /** Memory size MB. Default 512. */
  memorySize?: number;
  /** Timeout seconds. Default 30. */
  timeout?: number;
  /** Optional environment variables baked into the Lambda config (not the image). */
  envVars?: Record<string, string>;
  /** Extra IAM managed policy ARNs to attach to the exec role. Partition-qualified ARNs are preferred. */
  extraManagedPolicyArns?: string[];

  // ── VPC support (matches deploy/main.tf pattern) ──────────────────────────
  /**
   * Name tag of the VPC subnet. When set, renders data.aws_subnet + vpc_config
   * on the Lambda. Required for GHE/private-network access.
   */
  subnetNameTag?: string;
  /** SecurityGroup GroupName to look up when VPC is enabled. */
  securityGroupName?: string;

  // ── CodeBuild integration ─────────────────────────────────────────────────
  /**
   * When set, generates an `aws_codebuild_project` that the Lambda can trigger
   * (e.g. for long-running jobs that exceed the 15-min Lambda timeout).
   * Also generates IAM policies: Lambda→StartBuild/BatchGetBuilds.
   */
  codebuildProjectName?: string;
  /**
   * Name (or ARN) of the IAM role for the CodeBuild project. When not set,
   * a minimal role named `${functionName}-codebuild-role` is created.
   */
  codebuildRoleName?: string;
  /**
   * Secrets Manager secret name holding a GitHub token that the Lambda (or
   * CodeBuild) needs. When set, renders an IAM policy for GetSecretValue.
   */
  githubTokenSecretName?: string;
}

const DEFAULT_BASE_IMAGE = 'public.ecr.aws/lambda/python:3.12';

export function lambdaImagePackerHcl(inputs: LambdaImageScaffoldInputs): string {
  const baseImage = inputs.baseImage ?? DEFAULT_BASE_IMAGE;
  return `# Generated by terraform-workspace. Builds the Lambda container image
# and pushes it to the ECR repository created by ecr.tf.
#
# Run via packer-pipeline (see build.hcl) — not directly with \`packer build\`.

packer {
  required_plugins {
    docker = {
      source  = "github.com/hashicorp/docker"
      version = "~> 1.0"
    }
  }
}

variable "image_repo" {
  type        = string
  description = "ECR repository URI (account.dkr.ecr.region.amazonaws.com/repo)."
}

variable "image_tag" {
  type    = string
  default = "latest"
}

source "docker" "lambda" {
  image  = "${baseImage}"
  commit = true
  changes = [
    "WORKDIR /var/task",
    "CMD [\\"${inputs.handler ?? 'handler.lambda_handler'}\\"]",
  ]
}

build {
  name    = "${inputs.functionName}"
  sources = ["source.docker.lambda"]

  provisioner "file" {
    source      = "src/"
    destination = "/var/task/"
  }

  provisioner "shell" {
    inline = [
      "if [ -f /var/task/requirements.txt ]; then pip install --no-cache-dir -r /var/task/requirements.txt -t /var/task; fi",
    ]
  }

  post-processors {
    post-processor "docker-tag" {
      repository = var.image_repo
      tags       = [var.image_tag]
    }
    post-processor "docker-push" {
      ecr_login    = true
      login_server = var.image_repo
    }
  }
}
`;
}

export function lambdaImageBuildHcl(inputs: LambdaImageScaffoldInputs): string {
  return `# Consumed by the packer-pipeline CLI. See https://github.com/djaboxx/packer-pipeline.
packer_pipeline {
  repo_path             = "."
  packer_template_file  = "packer.pkr.hcl"
  s3_bucket             = "${inputs.packerSourceBucket}"
  codebuild_project_name = "${inputs.packerCodebuildProject}"
  create_role           = false
  environment_variables = {
    AWS_REGION = "${inputs.region}"
  }
}
`;
}

export function lambdaImageEcrTf(inputs: LambdaImageScaffoldInputs): string {
  const vpcDataSources = inputs.subnetNameTag ? `
# VPC lookups — resolved by name/tag so no account IDs are hardcoded
data "aws_subnet" "lambda" {
  filter {
    name   = "tag:Name"
    values = ["${inputs.subnetNameTag}"]
  }
}

data "aws_security_group" "lambda" {
  filter {
    name   = "group-name"
    values = ["${inputs.securityGroupName ?? 'default'}"]
  }
}
` : '';

  return `# Generated by terraform-workspace.
terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

provider "aws" {
  region = "${inputs.region}"
}

data "aws_caller_identity" "current" {}
data "aws_partition"       "current" {}
data "aws_region"          "current" {}
${vpcDataSources}
resource "aws_ecr_repository" "fn" {
  name                 = "${inputs.functionName}"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }
}

resource "aws_ecr_lifecycle_policy" "fn" {
  repository = aws_ecr_repository.fn.name
  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep last 10 tagged images"
        selection = {
          tagStatus      = "tagged"
          tagPatternList = ["*"]
          countType      = "imageCountMoreThan"
          countNumber    = 10
        }
        action = { type = "expire" }
      },
      {
        rulePriority = 2
        description  = "Expire untagged after 14 days"
        selection = {
          tagStatus   = "untagged"
          countType   = "sinceImagePushed"
          countUnit   = "days"
          countNumber = 14
        }
        action = { type = "expire" }
      }
    ]
  })
}

output "image_repo" {
  description = "ECR repository URI to pass as -var=image_repo to packer build."
  value       = aws_ecr_repository.fn.repository_url
}
`;
}

export function lambdaImageLambdaTf(inputs: LambdaImageScaffoldInputs): string {
  const envBlock = inputs.envVars && Object.keys(inputs.envVars).length > 0
    ? `\n  environment {\n    variables = {\n${Object.entries(inputs.envVars)
        .map(([k, v]) => `      ${k} = ${JSON.stringify(v)}`)
        .join('\n')}\n    }\n  }\n`
    : '';

  // Use partition-aware ARN — required for GovCloud (arn:aws-us-gov:iam::aws:policy/*)
  const basicExecArn = 'arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole';
  const vpcExecArn   = 'arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole';

  const extraPolicies = (inputs.extraManagedPolicyArns ?? [])
    .map((arn, i) => `resource "aws_iam_role_policy_attachment" "extra_${i}" {
  role       = aws_iam_role.fn.name
  policy_arn = "${arn}"
}
`)
    .join('\n');

  const vpcConfig = inputs.subnetNameTag ? `
  vpc_config {
    subnet_ids         = [data.aws_subnet.lambda.id]
    security_group_ids = [data.aws_security_group.lambda.id]
  }
` : '';

  const vpcPolicyAttachment = inputs.subnetNameTag ? `
resource "aws_iam_role_policy_attachment" "vpc_exec" {
  role       = aws_iam_role.fn.name
  policy_arn = "${vpcExecArn}"
}
` : '';

  const codebuildPolicy = inputs.codebuildProjectName ? `
# Allow Lambda to start and poll the CodeBuild job
resource "aws_iam_role_policy" "codebuild_access" {
  name = "${inputs.functionName}-codebuild-access"
  role = aws_iam_role.fn.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "StartAndPollBuild"
      Effect = "Allow"
      Action = [
        "codebuild:StartBuild",
        "codebuild:BatchGetBuilds",
      ]
      Resource = aws_codebuild_project.fn.arn
    }]
  })
}
` : '';

  const secretsPolicy = inputs.githubTokenSecretName ? `
# Allow Lambda to read the GitHub token from Secrets Manager
resource "aws_iam_role_policy" "github_token_access" {
  name = "${inputs.functionName}-github-token"
  role = aws_iam_role.fn.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid      = "ReadGitHubToken"
      Effect   = "Allow"
      Action   = ["secretsmanager:GetSecretValue"]
      Resource = "arn:\${data.aws_partition.current.partition}:secretsmanager:\${data.aws_region.current.name}:\${data.aws_caller_identity.current.account_id}:secret:${inputs.githubTokenSecretName}-*"
    }]
  })
}
` : '';

  return `# Generated by terraform-workspace.
#
# image_digest is set by the extension's "Build & Publish Lambda Image" command,
# which writes terraform.tfvars.json next to this file. Each image build pins
# the next \`terraform apply\` to an immutable digest (never a tag).

variable "image_digest" {
  type        = string
  description = "ECR image digest (sha256:...) to deploy. Set by the extension after a successful image build."
}

data "aws_iam_policy_document" "fn_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "fn" {
  name               = "${inputs.functionName}-exec"
  assume_role_policy = data.aws_iam_policy_document.fn_assume.json
}

resource "aws_iam_role_policy_attachment" "basic" {
  role       = aws_iam_role.fn.name
  policy_arn = "${basicExecArn}"
}
${vpcPolicyAttachment}
${extraPolicies}
${codebuildPolicy}
${secretsPolicy}
resource "aws_lambda_function" "fn" {
  function_name = "${inputs.functionName}"
  role          = aws_iam_role.fn.arn
  package_type  = "Image"
  image_uri     = "\${aws_ecr_repository.fn.repository_url}@\${var.image_digest}"
  memory_size   = ${inputs.memorySize ?? 512}
  timeout       = ${inputs.timeout ?? 30}
${vpcConfig}${envBlock}}

output "function_arn" {
  value = aws_lambda_function.fn.arn
}

output "function_name" {
  value = aws_lambda_function.fn.function_name
}
`;
}

/**
 * Generates the optional CodeBuild project resource.
 * Only rendered when `inputs.codebuildProjectName` is set.
 * Matches the deploy/main.tf `aws_codebuild_project.eks_repo_creator` pattern.
 */
export function lambdaImageCodebuildTf(inputs: LambdaImageScaffoldInputs): string | null {
  if (!inputs.codebuildProjectName) return null;

  const roleBlock = inputs.codebuildRoleName
    ? `data "aws_iam_role" "codebuild" {
  name = "${inputs.codebuildRoleName}"
}
`
    : `resource "aws_iam_role" "codebuild" {
  name = "${inputs.functionName}-codebuild-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "codebuild.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "codebuild_logs" {
  name = "codebuild-logs"
  role = aws_iam_role.codebuild.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "CloudWatchLogs"
      Effect = "Allow"
      Action = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
      Resource = "arn:\${data.aws_partition.current.partition}:logs:\${data.aws_region.current.name}:\${data.aws_caller_identity.current.account_id}:log-group:/aws/codebuild/${inputs.codebuildProjectName}:*"
    }]
  })
}
`;

  const roleArnRef = inputs.codebuildRoleName
    ? 'data.aws_iam_role.codebuild.arn'
    : 'aws_iam_role.codebuild.arn';

  const vpcBlock = inputs.subnetNameTag ? `
  vpc_config {
    vpc_id             = data.aws_subnet.lambda.vpc_id
    subnets            = [data.aws_subnet.lambda.id]
    security_group_ids = [data.aws_security_group.lambda.id]
  }
` : '';

  return `# Generated by terraform-workspace — CodeBuild project for ${inputs.codebuildProjectName}.
# This project is triggered by the Lambda for long-running jobs that exceed the
# 15-minute Lambda timeout. The Lambda starts the build and polls BatchGetBuilds.

${roleBlock}
resource "aws_codebuild_project" "fn" {
  name          = "${inputs.codebuildProjectName}"
  description   = "Triggered by Lambda ${inputs.functionName} for long-running operations."
  build_timeout = 15
  service_role  = ${roleArnRef}

  source {
    type      = "NO_SOURCE"
    buildspec = file("\${path.module}/buildspec.yml")
  }

  environment {
    compute_type    = "BUILD_GENERAL1_SMALL"
    image           = "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
    type            = "LINUX_CONTAINER"
    privileged_mode = false
  }

  artifacts {
    type = "NO_ARTIFACTS"
  }
${vpcBlock}
  tags = var.tags
}
`;
}

/** Skeleton handler. Only written if `src/handler.py` doesn't already exist. */
export function lambdaHandlerSkeleton(inputs: LambdaImageScaffoldInputs): string {
  return `"""${inputs.functionName} — generated handler skeleton.

Replace this with your real handler. The image build (packer.pkr.hcl) copies
everything under src/ into /var/task and runs \`pip install -r requirements.txt\`
if the file exists.
"""

import json
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)


def lambda_handler(event, context):
    logger.info("event=%s", json.dumps(event, default=str))
    return {
        "statusCode": 200,
        "body": json.dumps({"ok": True}),
    }
`;
}

export function lambdaImageRequirementsTxt(): string {
  return `# Pin runtime deps here. The packer build runs \`pip install -r requirements.txt\`
# and copies the result into /var/task.
`;
}
