/**
 * Generators for an AWS Lambda container image pipeline that mirrors the
 * Terraform CodeBuild executor pattern (see `src/workflows/Scaffolders.ts`):
 *
 *   - A Packer template (`packer.pkr.hcl`) that builds the function image
 *     using the amazon-ecr source.
 *   - A `build.hcl` consumed by the existing `packer-pipeline` CLI / CodeBuild
 *     project, so users keep using their already-provisioned image-build
 *     pipeline rather than us reinventing one.
 *   - Terraform: ECR repo (lifecycle policy), IAM exec role, and
 *     `aws_lambda_function` with `package_type = "Image"` pinned by digest
 *     via a `var.image_digest` so the next `terraform apply` after a fresh
 *     image build picks it up deterministically.
 *   - A `src/handler.py` skeleton (only written if missing).
 *
 * Pure string generation — no I/O. The caller is responsible for writing
 * files, prompting the user, etc.
 */

export interface LambdaImageScaffoldInputs {
  /** Logical function name. Used for the directory, ECR repo, and Lambda name. */
  functionName: string;
  /** AWS region the Lambda + ECR repo live in. */
  region: string;
  /** S3 bucket + key the packer-pipeline CodeBuild project reads sources from. */
  packerSourceBucket: string;
  /** Name of the existing packer-pipeline CodeBuild project to dispatch into. */
  packerCodebuildProject: string;
  /** Base image for the Lambda runtime. Default: `public.ecr.aws/lambda/python:3.12`. */
  baseImage?: string;
  /** Lambda handler entrypoint. Default: `handler.lambda_handler`. */
  handler?: string;
  /** Memory size MB. Default 512. */
  memorySize?: number;
  /** Timeout seconds. Default 30. */
  timeout?: number;
  /** Optional environment variables baked into the Lambda config (not the image). */
  envVars?: Record<string, string>;
  /** Extra IAM managed policy ARNs to attach to the exec role (in addition to AWSLambdaBasicExecutionRole). */
  extraManagedPolicyArns?: string[];
}

const DEFAULT_BASE_IMAGE = 'public.ecr.aws/lambda/python:3.12';

export function lambdaImagePackerHcl(inputs: LambdaImageScaffoldInputs): string {
  const baseImage = inputs.baseImage ?? DEFAULT_BASE_IMAGE;
  return `# Generated by terraform-workspace. Builds the Lambda container image
# and pushes it to the ECR repository created by ecr.tf.
#
# Run via packer-pipeline (see build.hcl) — not directly with \`packer build\`.

packer {
  required_plugins {
    docker = {
      source  = "github.com/hashicorp/docker"
      version = "~> 1.0"
    }
  }
}

variable "image_repo" {
  type        = string
  description = "ECR repository URI (account.dkr.ecr.region.amazonaws.com/repo)."
}

variable "image_tag" {
  type    = string
  default = "latest"
}

source "docker" "lambda" {
  image  = "${baseImage}"
  commit = true
  changes = [
    "WORKDIR /var/task",
    "CMD [\\"${inputs.handler ?? 'handler.lambda_handler'}\\"]",
  ]
}

build {
  name    = "${inputs.functionName}"
  sources = ["source.docker.lambda"]

  provisioner "file" {
    source      = "src/"
    destination = "/var/task/"
  }

  provisioner "shell" {
    inline = [
      "if [ -f /var/task/requirements.txt ]; then pip install --no-cache-dir -r /var/task/requirements.txt -t /var/task; fi",
    ]
  }

  post-processors {
    post-processor "docker-tag" {
      repository = var.image_repo
      tags       = [var.image_tag]
    }
    post-processor "docker-push" {
      ecr_login    = true
      login_server = var.image_repo
    }
  }
}
`;
}

export function lambdaImageBuildHcl(inputs: LambdaImageScaffoldInputs): string {
  return `# Consumed by the packer-pipeline CLI. See https://github.com/djaboxx/packer-pipeline.
packer_pipeline {
  repo_path             = "."
  packer_template_file  = "packer.pkr.hcl"
  s3_bucket             = "${inputs.packerSourceBucket}"
  codebuild_project_name = "${inputs.packerCodebuildProject}"
  create_role           = false
  environment_variables = {
    AWS_REGION = "${inputs.region}"
  }
}
`;
}

export function lambdaImageEcrTf(inputs: LambdaImageScaffoldInputs): string {
  return `# Generated by terraform-workspace.
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.40" }
  }
}

provider "aws" {
  region = "${inputs.region}"
}

resource "aws_ecr_repository" "fn" {
  name                 = "${inputs.functionName}"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }
}

resource "aws_ecr_lifecycle_policy" "fn" {
  repository = aws_ecr_repository.fn.name
  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep last 10 tagged images"
        selection = {
          tagStatus     = "tagged"
          tagPatternList = ["*"]
          countType     = "imageCountMoreThan"
          countNumber   = 10
        }
        action = { type = "expire" }
      },
      {
        rulePriority = 2
        description  = "Expire untagged after 14 days"
        selection = {
          tagStatus   = "untagged"
          countType   = "sinceImagePushed"
          countUnit   = "days"
          countNumber = 14
        }
        action = { type = "expire" }
      }
    ]
  })
}

output "image_repo" {
  description = "ECR repository URI to pass as -var=image_repo to packer build."
  value       = aws_ecr_repository.fn.repository_url
}
`;
}

export function lambdaImageLambdaTf(inputs: LambdaImageScaffoldInputs): string {
  const envBlock = inputs.envVars && Object.keys(inputs.envVars).length > 0
    ? `\n  environment {\n    variables = {\n${Object.entries(inputs.envVars)
        .map(([k, v]) => `      ${k} = ${JSON.stringify(v)}`)
        .join('\n')}\n    }\n  }\n`
    : '';

  const extraPolicies = (inputs.extraManagedPolicyArns ?? [])
    .map((arn, i) => `resource "aws_iam_role_policy_attachment" "extra_${i}" {
  role       = aws_iam_role.fn.name
  policy_arn = "${arn}"
}
`)
    .join('\n');

  return `# Generated by terraform-workspace.
#
# image_digest is set by the extension's "Build & Publish Lambda Image" command,
# which writes terraform.tfvars.json next to this file. Each image build pins
# the next \`terraform apply\` to an immutable digest (never a tag).

variable "image_digest" {
  type        = string
  description = "ECR image digest (sha256:...) to deploy. Set by the extension after a successful image build."
}

data "aws_iam_policy_document" "fn_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "fn" {
  name               = "${inputs.functionName}-exec"
  assume_role_policy = data.aws_iam_policy_document.fn_assume.json
}

resource "aws_iam_role_policy_attachment" "basic" {
  role       = aws_iam_role.fn.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

${extraPolicies}
resource "aws_lambda_function" "fn" {
  function_name = "${inputs.functionName}"
  role          = aws_iam_role.fn.arn
  package_type  = "Image"
  image_uri     = "\${aws_ecr_repository.fn.repository_url}@\${var.image_digest}"
  memory_size   = ${inputs.memorySize ?? 512}
  timeout       = ${inputs.timeout ?? 30}
${envBlock}}

output "function_arn" {
  value = aws_lambda_function.fn.arn
}

output "function_name" {
  value = aws_lambda_function.fn.function_name
}
`;
}

/** Skeleton handler. Only written if `src/handler.py` doesn't already exist. */
export function lambdaHandlerSkeleton(inputs: LambdaImageScaffoldInputs): string {
  return `"""${inputs.functionName} — generated handler skeleton.

Replace this with your real handler. The image build (packer.pkr.hcl) copies
everything under src/ into /var/task and runs \`pip install -r requirements.txt\`
if the file exists.
"""

import json
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)


def lambda_handler(event, context):
    logger.info("event=%s", json.dumps(event, default=str))
    return {
        "statusCode": 200,
        "body": json.dumps({"ok": True}),
    }
`;
}

export function lambdaImageRequirementsTxt(): string {
  return `# Pin runtime deps here. The packer build runs \`pip install -r requirements.txt\`
# and copies the result into /var/task.
`;
}
